version: '3'

services:
  postgres:
    image: 'postgres:latest'
    ports:
      - 9920:5432
    environment:
      - POSTGRES_DB=gorm
      - POSTGRES_USER=gorm
      - POSTGRES_PASSWORD=gorm
  server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - database
    networks:
      - default
    ports:
    - "10000:10000"
    - "11000:11000"